### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by gmacario** [uchida/docker-markdown-pdf#1]
Hello,

Thanks for the auchida/markdown-pdf Docker image!

I tried to run the container to convert the README.md of this project to PDF but I got a strange warning which I could not figure out

```
gmacario@itm-gmacario-w7:~/github/uchida $ git clone https://github.com/uchida/docker-markdown-pdf
Cloning into 'docker-markdown-pdf'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
gmacario@itm-gmacario-w7:~/github/uchida $ cd docker-markdown-pdf/
gmacario@itm-gmacario-w7:~/github/uchida/docker-markdown-pdf (master)$ ls -la README.md
-rw-rw-r-- 1 gmacario gmacario 1519 apr 18 12:09 README.md
gmacario@itm-gmacario-w7:~/github/uchida/docker-markdown-pdf (master)$ docker run -v ${PWD}:/opt/docs auchida/markdown-pdf markdown-pdf -o README.pdf README.md
(node) warning: possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at SeriesStream.addListener (events.js:239:17)
    at SeriesStream.Readable.on (_stream_readable.js:680:33)
    at SeriesStream.on (/usr/local/lib/node_modules/markdown-pdf/node_modules/stream-from-to/node_modules/series-stream/index.js:12:38)
    at SeriesStream.once (events.js:265:8)
    at SeriesStream.Readable.pipe (_stream_readable.js:486:9)
    at SeriesStream.pipe (/usr/local/lib/node_modules/markdown-pdf/node_modules/stream-from-to/node_modules/series-stream/index.js:22:30)
    at /usr/local/lib/node_modules/markdown-pdf/node_modules/stream-from-to/index.js:101:25
    at /usr/local/lib/node_modules/markdown-pdf/node_modules/stream-from-to/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
gmacario@itm-gmacario-w7:~/github/uchida/docker-markdown-pdf (master)*$
```

Any suggestions?

FYI: I am running latest Docker-ce on Ubuntu 16.04.4 LTS 64-bit:

```
gmacario@itm-gmacario-w7:~/github/uchida $ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
gmacario@itm-gmacario-w7:~/github/uchida $ docker --version
Docker version 18.03.0-ce, build 0520e24
gmacario@itm-gmacario-w7:~/github/uchida $
```

**Comment by hbraux** [comment]
Use this Dockerfile to build an up to date (Node10) image that fixes this memory warning


```
FROM node:10
RUN  apt-get update && apt-get install -y fonts-noto-cjk\
 && rm -rf /var/lib/apt/lists/*
RUN npm config set user 0 && npm -g install phantomjs-prebuilt
RUN npm install -g markdown-pdf@10.0.0\
 && rm -rf ~/.npm/cache/*\
 && mkdir -p /opt/docs
WORKDIR /opt/docs
COPY fonts.conf /etc/fonts/conf.d/99-local.conf
ENV NODE_PATH /usr/local/lib/node_modules
CMD ["/bin/bash"]
```
